package org.team9432.resources.drive

import com.ctre.phoenix6.configs.*
import com.ctre.phoenix6.mechanisms.swerve.SwerveDrivetrainConstants
import com.ctre.phoenix6.mechanisms.swerve.SwerveModule.ClosedLoopOutputType
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstants
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstants.SteerFeedbackType
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstantsFactory
import edu.wpi.first.math.util.Units

// Generated by the Tuner X Swerve Project Generator (and then turned into kotlin)
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
object TunerConstants {
    // Both sets of gains need to be tuned to your individual robot.
    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    val steerGains: Slot0Configs = Slot0Configs()
        .withKP(100.0).withKI(0.0).withKD(0.2)
        .withKS(0.0).withKV(1.5).withKA(0.0)

    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    val driveGains: Slot0Configs = Slot0Configs()
        .withKP(3.0).withKI(0.0).withKD(0.0)
        .withKS(0.0).withKV(0.0).withKA(0.0)

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    val steerClosedLoopOutput = ClosedLoopOutputType.Voltage

    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    val driveClosedLoopOutput = ClosedLoopOutputType.Voltage

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    const val kSlipCurrentA = 60.0

    // Initial configs for the drive and steer motors and the CANcoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    val driveInitialConfigs = TalonFXConfiguration()
        .withCurrentLimits(
            CurrentLimitsConfigs()
//                .withStatorCurrentLimit(60.0)
//                .withStatorCurrentLimitEnable(true)
        )
    val steerInitialConfigs: TalonFXConfiguration = TalonFXConfiguration()
        .withCurrentLimits(
            CurrentLimitsConfigs() // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(50.0)
                .withStatorCurrentLimitEnable(true)
        )
    val cancoderInitialConfigs = CANcoderConfiguration()

    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    val pigeonConfigs: Pigeon2Configuration? = null

    // Theoretical free speed (m/s) at 12v applied output;
    // This needs to be tuned to your individual robot
    const val kSpeedAt12VoltsMps: Double = 5.19

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    const val kCoupleRatio = 0.0

    const val kDriveGearRatio = 5.9
    const val kSteerGearRatio = 23.07692307692308
    const val kWheelRadiusInches = 3.84 / 2

    const val kInvertLeftSide = false
    const val kInvertRightSide = true

    const val kCANbusName = "Drivetrain"
    const val kPigeonId = 0


    // These are only used for simulation
    const val kSteerInertia = 0.00001
    const val kDriveInertia = 0.001

    // Simulated voltage necessary to overcome friction
    const val kSteerFrictionVoltage = 0.25
    const val kDriveFrictionVoltage = 0.25

    val DrivetrainConstants: SwerveDrivetrainConstants = SwerveDrivetrainConstants()
        .withCANbusName(kCANbusName)
        .withPigeon2Id(kPigeonId)
        .withPigeon2Configs(pigeonConfigs)

    val ConstantCreator: SwerveModuleConstantsFactory = SwerveModuleConstantsFactory()
        .withDriveMotorGearRatio(kDriveGearRatio)
        .withSteerMotorGearRatio(kSteerGearRatio)
        .withWheelRadius(kWheelRadiusInches)
        .withSlipCurrent(kSlipCurrentA)
        .withSteerMotorGains(steerGains)
        .withDriveMotorGains(driveGains)
        .withSteerMotorClosedLoopOutput(steerClosedLoopOutput)
        .withDriveMotorClosedLoopOutput(driveClosedLoopOutput)
        .withSpeedAt12VoltsMps(kSpeedAt12VoltsMps)
        .withSteerInertia(kSteerInertia)
        .withDriveInertia(kDriveInertia)
        .withSteerFrictionVoltage(kSteerFrictionVoltage)
        .withDriveFrictionVoltage(kDriveFrictionVoltage)
        .withFeedbackSource(SteerFeedbackType.FusedCANcoder)
        .withCouplingGearRatio(kCoupleRatio)
        .withDriveMotorInitialConfigs(driveInitialConfigs)
        .withSteerMotorInitialConfigs(steerInitialConfigs)
        .withCANcoderInitialConfigs(cancoderInitialConfigs)


    // Front Left
    const val kFrontLeftDriveMotorId = 1
    const val kFrontLeftSteerMotorId = 2
    const val kFrontLeftEncoderId = 1
    const val kFrontLeftEncoderOffset = 0.2470703125
    const val kFrontLeftSteerInvert = true

    const val kFrontLeftXPosInches = 6.875
    const val kFrontLeftYPosInches = 9.875

    // Front Right
    const val kFrontRightDriveMotorId = 3
    const val kFrontRightSteerMotorId = 4
    const val kFrontRightEncoderId = 2
    const val kFrontRightEncoderOffset = 0.306884765625
    const val kFrontRightSteerInvert = true

    const val kFrontRightXPosInches = 6.875
    const val kFrontRightYPosInches = -9.875

    // Back Left
    const val kBackLeftDriveMotorId = 5
    const val kBackLeftSteerMotorId = 6
    const val kBackLeftEncoderId = 3
    const val kBackLeftEncoderOffset = -0.056884765625
    const val kBackLeftSteerInvert = true

    const val kBackLeftXPosInches = -6.875
    const val kBackLeftYPosInches = 9.875

    // Back Right
    const val kBackRightDriveMotorId = 7
    const val kBackRightSteerMotorId = 8
    const val kBackRightEncoderId = 4
    const val kBackRightEncoderOffset = 0.012798828125
    const val kBackRightSteerInvert = true

    const val kBackRightXPosInches = -6.875
    const val kBackRightYPosInches = -9.875


    val FrontLeft: SwerveModuleConstants = ConstantCreator.createModuleConstants(
        kFrontLeftSteerMotorId,
        kFrontLeftDriveMotorId,
        kFrontLeftEncoderId,
        kFrontLeftEncoderOffset,
        Units.inchesToMeters(kFrontLeftXPosInches),
        Units.inchesToMeters(kFrontLeftYPosInches),
        kInvertLeftSide
    ).withSteerMotorInverted(kFrontLeftSteerInvert)

    val FrontRight: SwerveModuleConstants = ConstantCreator.createModuleConstants(
        kFrontRightSteerMotorId,
        kFrontRightDriveMotorId,
        kFrontRightEncoderId,
        kFrontRightEncoderOffset,
        Units.inchesToMeters(kFrontRightXPosInches),
        Units.inchesToMeters(kFrontRightYPosInches),
        kInvertRightSide
    ).withSteerMotorInverted(kFrontRightSteerInvert)

    val BackLeft: SwerveModuleConstants = ConstantCreator.createModuleConstants(
        kBackLeftSteerMotorId,
        kBackLeftDriveMotorId,
        kBackLeftEncoderId,
        kBackLeftEncoderOffset,
        Units.inchesToMeters(kBackLeftXPosInches),
        Units.inchesToMeters(kBackLeftYPosInches),
        kInvertLeftSide
    ).withSteerMotorInverted(kBackLeftSteerInvert)

    val BackRight: SwerveModuleConstants = ConstantCreator.createModuleConstants(
        kBackRightSteerMotorId,
        kBackRightDriveMotorId,
        kBackRightEncoderId,
        kBackRightEncoderOffset,
        Units.inchesToMeters(kBackRightXPosInches),
        Units.inchesToMeters(kBackRightYPosInches),
        kInvertRightSide
    ).withSteerMotorInverted(kBackRightSteerInvert)
}
